name: Test Windows/macOS Build

on:
  pull_request:
    branches:
    - deploy
    - master
  push:
    branches:
      - master
      - deploy
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install wget zip unzip
    - name: Download Godot Headless
      run: |
        wget -q https://downloads.tuxfamily.org/godotengine/3.1.1/Godot_v3.1.1-stable_linux_headless.64.zip
        unzip Godot_v3.1.1-stable_linux_headless.64.zip
        mv Godot_v3.1.1-stable_linux_headless.64 godot
        chmod +x godot
        
    - name: Download Godot Export Templates
      run: |
        wget -q https://downloads.tuxfamily.org/godotengine/3.1.1/Godot_v3.1.1-stable_export_templates.tpz
        mkdir -p ~/.local/share/godot/templates
        unzip Godot_v3.1.1-stable_export_templates.tpz -d ~/.local/share/godot/templates
        mv ~/.local/share/godot/templates/templates ~/.local/share/godot/templates/3.1.1.stable
    - name: Export win64 build
      run: |
        mkdir -p $GITHUB_WORKSPACE/builds
        ./godot --path $GITHUB_WORKSPACE --export "$GITHUB_WORKSPACE/builds" "win64/ProjectTesseract.exe"
    - name: Export macOS build
      run: |
        ./godot --path $GITHUB_WORKSPACE --export "$GITHUB_WORKSPACE/builds" "macOS/ProjectTesseract.app"
    - uses: actions/upload-artifact@master
      with:
        name: Windows_64
        path: $GITHUB_WORKSPACE/builds
    - uses: actions/upload-artifact@master
      with:
        name: macOS
        path: $GITHUB_WORKSPACE/builds
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: $GITHUB_WORKSPACE/builds
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

